graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors: false
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true