version: '3.5'

services:
  #https://hub.docker.com/r/minio/minio/
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "password"
    entrypoint: sh
    command: -c 'mkdir -p /storage/default && /usr/bin/minio server /storage'
    volumes:
      - .minio:/storage
    ports:
      - 9000:9000

  #https://github.com/jgraph/docker-drawio
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443